/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICapPool__factory } from "./ICapPool__factory";
export { ICapRewards__factory } from "./ICapRewards__factory";
