/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stratFeeManagerSol from "./StratFeeManager.sol";
export type { stratFeeManagerSol };
export type { StratFeeManagerInitializable } from "./StratFeeManagerInitializable";
