/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StratFeeManager } from "./StratFeeManager";
export type { StratFeeManagerInitializable } from "./StratFeeManagerInitializable";
