/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBeefyVault,
  IBeefyVaultInterface,
} from "../../../../contracts/interfaces/gmx/IBeefyVault";

const _abi = [
  {
    inputs: [],
    name: "stratCandidate",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "implementation",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "proposedTime",
            type: "uint256",
          },
        ],
        internalType: "struct IBeefyVault.StratCandidate",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "strategy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBeefyVault__factory {
  static readonly abi = _abi;
  static createInterface(): IBeefyVaultInterface {
    return new utils.Interface(_abi) as IBeefyVaultInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBeefyVault {
    return new Contract(address, _abi, signerOrProvider) as IBeefyVault;
  }
}
