/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFeeStakedOLP,
  IFeeStakedOLPInterface,
} from "../../../../contracts/interfaces/gmx/IFeeStakedOLP";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "depositToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "stake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "depositToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "unstake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IFeeStakedOLP__factory {
  static readonly abi = _abi;
  static createInterface(): IFeeStakedOLPInterface {
    return new utils.Interface(_abi) as IFeeStakedOLPInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFeeStakedOLP {
    return new Contract(address, _abi, signerOrProvider) as IFeeStakedOLP;
  }
}
