/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGMXStrategy,
  IGMXStrategyInterface,
} from "../../../../contracts/interfaces/gmx/IGMXStrategy";

const _abi = [
  {
    inputs: [],
    name: "acceptTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGMXStrategy__factory {
  static readonly abi = _abi;
  static createInterface(): IGMXStrategyInterface {
    return new utils.Interface(_abi) as IGMXStrategyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGMXStrategy {
    return new Contract(address, _abi, signerOrProvider) as IGMXStrategy;
  }
}
